=== yeKcim/warmux/old/wormux-0.8alpha1/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,surface+,name,water,nb_mine,nb_barrel?,is_open,infinite_background?, (sprite,wind)?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

=== yeKcim/warmux/community_maps/basemilitaire/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>kiriep</name>
		<nickname>kiriep</nickname>
		<email>kiriep@gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="sky.jpg" />
	<surface name="map" file="background.png" />
	<surface name="preview" file="preview.jpg" />


	<name>Base Militaire</name>
	<water>no</water>
	<nb_barrel>10</nb_barrel>
	<nb_mine>10</nb_mine>
	<is_open>1</is_open>
    
  <sprite name="wind_particle">
    <image file="grenadefrag.png">
      <grid pos="0,0" size="14,16" array="1,1"/>
    </image>
  </sprite>
 
  <wind>
    <nbr_sprite>5</nbr_sprite>
    <need_flip>1</need_flip>
    <mass>0.5</mass>
    <wind_factor>3.0</wind_factor>
    <air_resist_factor>0.1</air_resist_factor>
    <gravity_factor>0.5</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>1.5</rebound_factor>
  </wind>
	
</resources>

=== yeKcim/warmux/old/wormux-0.8.3/data/map/oktopus/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Oktopus</name>
  <water>water</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>

  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="500" y="500" />
  <point name="lower_right_pad" x="500" y="0" />

  <sprite name="wind_particle">
    <image file="bulle.png">
      <grid pos="0,0" size="50,50" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>60</nbr_sprite>
    <mass>1</mass>
    <wind_factor>2</wind_factor>
    <air_resist_factor>0.5</air_resist_factor>
    <gravity_factor>-1</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>1.3</rebound_factor>
  </wind>

  <music_playlist>sea</music_playlist>

</resources>

=== yeKcim/warmux/old/wormux-0.9.1/data/map/montagnes/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Jeoire de Chassey</name>
   <nickname>Akela NDE</nickname>
   <email>jeoire[a]chassey.net</email>
   <country>France</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Montagnes</name>
 <water>water</water>
 <nb_mine>5</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="flocon.png">
     <grid pos="0,0" size="20,18" array="1,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>6</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>1.0</mass>
   <wind_factor>8.5</wind_factor>
   <air_resist_factor>0.1</air_resist_factor>
   <gravity_factor>0.2</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>2.1</rebound_factor>
 </wind>
 
 <!--<music_playlist>NAMEOFMUSICFILE</music_playlist>-->
 
</resources>

=== yeKcim/warmux/old/wormux-0.8.2/data/map/monkeybubbleworld/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰ and Olivier Boyer</name>
    <nickname>yeKcim and Zi Olive</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="monkeybubbleworld.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Monkey-Bubble World</name>
  <water>dirtywater</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1400" y="1100" />
  <point name="lower_right_pad" x="1400" y="0" />

  <sprite name="wind_particle">
    <image file="feuille.png">
      <grid pos="0,0" size="50,50" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>35</nbr_sprite>
    <need_flip>1</need_flip>
    <rotation_speed>0.02</rotation_speed>
    <mass>2.0</mass>
    <wind_factor>5.5</wind_factor>
    <air_resist_factor>0.5</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>1.3</rebound_factor>
  </wind>

  <music_playlist>monkey</music_playlist>

</resources>

=== yeKcim/warmux/community_maps/minersmayhem/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>America</country>
 </author>
 
 <surface name="sky" file="cavebackground.jpg" />
 <surface name="map" file="cave.png" />
 <surface name="preview" file="cavepreview.jpg" />
 
 <name>Miner's Mayhem</name>
 <water>water</water>
 <nb_mine>0</nb_mine>
 <is_open>0</is_open>
 
 <sprite name="wind_particle">
   <image file="gem.png">
     <grid pos="0,0" size="55,52" array="1,1"/>
   </image>
 </sprite>

 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="900" y="800" /> 
 <point name="lower_right_pad" x="900" y="0" /> 

 <wind>
   <nbr_sprite>15</nbr_sprite>
   <need_flip>0</need_flip>
   <mass>1.0</mass>
   <wind_factor>0.2</wind_factor>
   <rotation_speed>0.04</rotation_speed>
   <air_resist_factor>0.05</air_resist_factor>
   <gravity_factor>0.05</gravity_factor>
   <rebounding>false</rebounding>
   <rebound_factor>0.0</rebound_factor>

 </wind>
</resources>

=== yeKcim/warmux/old/wormux-0.8alpha1/data/map/halloween/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lawrenceazzoug AT wanadoo.fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="noir_lune.jpg" />
  <surface name="map" file="halloween.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Halloween</name>
  <water>0</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>

    <sprite name="wind_particle">
      <image file="confetis.png">
        <grid pos="15,0" size="48,36" array="48,1"/>
      </image>
      <animation speed="100" />
    </sprite>

  <wind>
    <nbr_sprite>10</nbr_sprite>
    <mass>4.3</mass>
    <wind_factor>2.3</wind_factor>
    <air_resist_factor>0.1</air_resist_factor>
    <gravity_factor>0.1</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>1.3</rebound_factor>
  </wind>

</resources>

=== yeKcim/warmux/old/wormux-0.9.1/data/map/construction/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT wormux.org</email>
    <country>France</country>
  </author>

  <surface name="sky"     file="sky.jpg" /> 

  <sky_layer>3</sky_layer>
  <surface name="sky_layer_0" file="sky0.png" />
  <surface name="sky_layer_1" file="sky1.png" />
  <surface name="sky_layer_2" file="sky2.png" />

  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Construction</name>
  <water>water</water>
  <nb_mine>4</nb_mine>
  <nb_barrel>2</nb_barrel>
  <is_open>1</is_open>
  <music_playlist>construction</music_playlist>

  <sprite name="wind_particle">
     <image file="raindrop.png">
       <grid pos="0,0" size="3,101" array="1,1"/>
     </image>
  </sprite>
 
  <wind>
     <nbr_sprite>20</nbr_sprite>
     <need_flip>0</need_flip>
     <mass>1.0</mass>
     <wind_factor>0.7</wind_factor>
     <air_resist_factor>0.01</air_resist_factor>
     <gravity_factor>0.3</gravity_factor>
     <rebounding>false</rebounding>
     <rebound_factor>0.0</rebound_factor>
     <auto_align_particle>true</auto_align_particle>
  </wind>

</resources>

=== yeKcim/warmux/old/wormux-0.9.0/data/map/paint/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT wormux.org</email>
    <country>France</country>
  </author>

  <surface name="sky"     file="sky.png" />
  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Paint</name>
  <water>water</water>
  <nb_mine>4</nb_mine>
  <nb_barrel>2</nb_barrel>
  <is_open>1</is_open>

</resources>
