=== yeKcim/warmux/old/wormux-0.8alpha1/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,surface+,name,water,nb_mine,nb_barrel?,is_open,infinite_background?, (sprite,wind)?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

=== yeKcim/warmux/old/wormux-0.8beta1/data/map/wildwestdv/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Tomasz Majbaum</name>
		<nickname>Ahriman</nickname>
		<email>anunnaki AT o2.pl</email>
		<country>Poland</country>
	</author>

  <surface name="sky" file="backgr.jpg" />
  <surface name="map" file="wildwestdv.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Wild West - Death Valley</name>
  <water>0</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
</resources>

=== yeKcim/warmux/old/wormux-0.9.0/data/map/arcaderoom/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Maciej Mrozi≈Ñski</name>
   <nickname>alzen</nickname>
   <email>mynick2_at_o2_dot_pl</email>
   <country>Poland</country>
 </author>

 <surface name="sky" file="background.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Arcade Room</name>
  <water>water</water>
 <nb_mine>6</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="wind_particle.png">
     <grid pos="0,0" size="59,59" array="124,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>40</nbr_sprite>
   <need_flip>0</need_flip>
   <rotation_speed>0.00</rotation_speed>
   <mass>2.0</mass>
   <wind_factor>6.5</wind_factor>
   <air_resist_factor>0.1</air_resist_factor>
   <gravity_factor>0.2</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>3.3</rebound_factor>
 </wind>
 
 <music_playlist>funfair</music_playlist>
 
</resources>

=== yeKcim/warmux/old/wormux-0.8beta2/data/map/pirates/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Michael PRAGER</name>
    <email>X_X_L AT gmx.net</email>
    <country>Germany</country>
  </author>

  <surface name="sky" file="islands.jpg" />
  <surface name="map" file="pirates.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Pirates</name>
  <water>1</water>
  <nb_mine>10</nb_mine>
  <is_open>1</is_open>

  <music_playlist>sea</music_playlist>
</resources>

=== yeKcim/warmux/old/warmux-11.01/data/map/junglemountain/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>America</country>
 </author>
 
 <surface name="sky" file="drseuss.jpg" />
 <surface name="map" file="dseuss_fg.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Jungle Mountain</name>
 <water>water</water>
 <nb_mine>0</nb_mine>
 <is_open>0</is_open>
 
 <sprite name="wind_particle">
   <image file="goo_drop.png">
     <grid size="34,49" array="1,1"/>
   </image>
 </sprite>

 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="900" y="1600" /> 
 <point name="lower_right_pad" x="900" y="0" /> 

   <wind>
     <nbr_sprite>20</nbr_sprite>
     <need_flip>0</need_flip>
     <mass>1.0</mass>
     <wind_factor>0.0</wind_factor>
     <air_resist_factor>0.005</air_resist_factor>
     <gravity_factor>0.1</gravity_factor>
     <rebounding>false</rebounding>
     <rebound_factor>0.0</rebound_factor>
       </wind>
</resources>

=== yeKcim/warmux/old/wormux-0.8.1/data/map/space2/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lawrenceazzoug AT wanadoo.fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Space 2</name>
  <water>0</water>
  <nb_mine>3</nb_mine>
  <is_open>0</is_open>
</resources>

=== yeKcim/warmux/old/wormux-0.9.0/data/map/bankiz/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <description>Inspired by bankiz artwork seen on nekeme website</description>
  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="bankiz.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Bankiz</name>
  <water>water</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="600" y="550" />
  <point name="lower_right_pad" x="600" y="0" />

  <sprite name="wind_particle">
    <image file="flocon.png">
      <grid pos="0,0" size="15,15" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>100</nbr_sprite>
    <need_flip>1</need_flip>

    <mass>3.0</mass>
    <wind_factor>8.5</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.2</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>3.3</rebound_factor>
  </wind>

  <music_playlist>sea</music_playlist>
</resources>

=== yeKcim/warmux/old/wormux-0.7.9/data/map/hell/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Tomasz Majbaum</name>
		<nickname>Ahriman</nickname>
		<email>anunnaki AT o2.pl</email>
		<country>Poland</country>
	</author>
	
	<surface name="sky" file="hellsky.jpg" />
	<surface name="map" file="hell.png" />
	<surface name="preview" file="preview.jpg" />
	
	<name>Hell</name>
	<water>0</water>
	<nb_mine>3</nb_mine>
	<is_open>1</is_open>
	
	<sprite name="wind_particle">
		<image file="bones.png">
			<grid pos="0,0" size="64,64" array="8,1"/>
		</image>
		<animation speed="50"/>
	</sprite>
	<wind>
		<nbr_sprite>10</nbr_sprite>
		<need_flip>0</need_flip>

    <mass>3.0</mass>
    <wind_factor>10.0</wind_factor>
    <air_resist_factor>1.0</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>1.0</rebound_factor>
	</wind>
</resources>
