=== yeKcim/warmux/old/wormux-0.8alpha1/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,surface+,name,water,nb_mine,nb_barrel?,is_open,infinite_background?, (sprite,wind)?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

=== yeKcim/warmux/old/wormux-0.8beta3/data/map/pumpkins/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>JS</name>
   <nickname>Jeese</nickname>
   <email>jeeseverly_AT_yahoo_DOT_fr</email>
   <country>france</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Pumpkins</name>
 <water>0</water>
 <nb_mine>8</nb_mine>
 <is_open>1</is_open>
   <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="500" y="500" />
  <point name="lower_right_pad" x="500" y="0" />

 <sprite name="wind_particle">
   <image file="feuille.png">
     <grid pos="0,0" size="63,63" array="1,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>6</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>5.0</mass>
   <wind_factor>8.5</wind_factor>
   <air_resist_factor>0.2</air_resist_factor>
   <gravity_factor>0.2</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>3.3</rebound_factor>
 </wind>
 
 <music_playlist>fear</music_playlist>
 
</resources>

=== yeKcim/warmux/community_maps/titanik/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>grospoisonaujambon</name>
   <nickname>inkey</nickname>
   <email>Lelitchie[AT]hotmail[DOT]fr</email>
   <country>france</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>titanik</name>
 <water>water</water>
 <nb_mine>5</nb_mine>
 <is_open>1</is_open>
 

</resources>

=== yeKcim/warmux/community_maps/theshire/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Benjamin Cluck</name>
		<nickname>Batmanifestdestiny</nickname>
		<email>I'm not gonna tell you</email>
		<country>America</country>
	</author>

	<surface name="sky" file="sky.jpg" />
	<surface name="map" file="background.png" />
	<surface name="preview" file="preview.jpg" />


	<name>The Shire</name>
	<water>no</water>
	<nb_mine>10</nb_mine>
	<is_open>0</is_open>

</resources>

=== yeKcim/warmux/old/wormux-0.9.2.1/data/map/chess/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT wormux.org</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" /> 

  <sky_layer>2</sky_layer>
  <surface name="sky_layer_0" file="sky0.png" />
  <surface name="sky_layer_1" file="sky1.png" />
  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="3000" y="1000" />
  <point name="lower_right_pad" x="3000" y="0" />

  <name>Chess</name>
  <water>water</water>
  <nb_mine>3</nb_mine>
  <nb_barrel>1</nb_barrel>
  <is_open>1</is_open>

</resources>

=== yeKcim/warmux/old/wormux-0.8.3/data/map/cheese/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="emmental.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Cheese</name>
  <water>no</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1400" y="1000" />
  <point name="lower_right_pad" x="1400" y="0" />

  <sprite name="wind_particle">
    <image file="minicheese.png">
      <grid pos="0,0" size="63,63" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>6</nbr_sprite>
    <need_flip>1</need_flip>

    <mass>5.0</mass>
    <wind_factor>8.5</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.2</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>3.3</rebound_factor>
  </wind>

  <music_playlist>funfair</music_playlist>
</resources>

=== yeKcim/warmux/old/wormux-0.9.0/data/map/apocalypse/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>SEBASTIEN MATHIER</name>
   <nickname>SEBASTIEN</nickname>
   <email>mathier AT hotmail.com</email>
   <country>Suisse</country>
 </author>
 
 <surface name="sky" file="apocalypse.jpg" />
 <surface name="map" file="apocalypse.png" />
 <surface name="preview" file="mini.jpg" />
 
 <name>Apocalypse</name>
 <water>lava</water>
 <nb_mine>12</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="vent.png">
     <grid pos="0,0" size="97,233" array="1,1"/>
   </image>
 </sprite>

 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="900" y="800" /> 
 <point name="lower_right_pad" x="900" y="0" /> 

 <wind>
   <nbr_sprite>10</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>3.0</mass>
   <wind_factor>0.1</wind_factor>
   <air_resist_factor>0.3</air_resist_factor>
   <gravity_factor>3</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>1.5</rebound_factor>

 </wind>
</resources>

=== yeKcim/warmux/old/wormux-0.7.9/data/map/cowland/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Alexandre NORMAN</name>
    <nickname>Xael</nickname>
    <email>norman AT xael.org</email>
    <country>France</country>
  </author>

  <surface name="sky" file="cowland_bg.jpg" />
  <surface name="map" file="cowland.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Cowland</name>
  <water>0</water>
  <nb_mine>3</nb_mine>
  <nb_barrel>1</nb_barrel>
  <is_open>1</is_open>

  <sprite name="wind_particle">
    <image file="nuage.png">
      <grid pos="0,0" size="128,64" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>10</nbr_sprite>
    <need_flip>true</need_flip>

    <mass>0.5</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.3</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>1.0</rebound_factor>
  </wind>
</resources>

=== yeKcim/warmux/old/wormux-0.8.1/data/map/crystal/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>C. Schalkwijk</name>
    <nickname>Papa.Coen</nickname>
    <email>Papa.Coen@gmail.com</email>
    <country>The Netherlands</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="crystal.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Crystal</name>
  <water>3</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1200" y="700" />
  <point name="lower_right_pad" x="1200" y="0" />
</resources>
